# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('vbCPP_rcpparma_hello_world', PACKAGE = 'vbCPP')
}

rcpparma_outerproduct <- function(x) {
    .Call('vbCPP_rcpparma_outerproduct', PACKAGE = 'vbCPP', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('vbCPP_rcpparma_innerproduct', PACKAGE = 'vbCPP', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('vbCPP_rcpparma_bothproducts', PACKAGE = 'vbCPP', x)
}

vbCPP <- function(X, K, maxIter = 2000L, tol = 1e-8) {
    .Call('vbCPP_vbCPP', PACKAGE = 'vbCPP', X, K, maxIter, tol)
}

